var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,ha,ia;
if(ea){var fs=require("fs"),ja=require("path");q=l?ja.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};ha=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);
process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(a){throw a;});h=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;if(!(b instanceof ka)){var c=b;b&&"object"==typeof b&&b.stack&&(c=[b,b.stack]);r("exiting due to exception: "+c)}process.exit(a)};g.inspect=function(){return"[Emscripten Module object]"}}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=
c;d.send(null)};g.print||console.log.bind(console);var r=g.printErr||console.warn.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(h=g.quit);var t;g.wasmBinary&&(t=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&la("no native wasm support detected");var ma,na=!1,oa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function w(a,b){if(a){var c=x,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&oa)a=oa.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function y(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0;return c-e}
function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var qa,x,ra,sa,z,ta,A,B;function ua(){var a=ma.buffer;g.HEAP8=qa=new Int8Array(a);g.HEAP16=ra=new Int16Array(a);g.HEAP32=z=new Int32Array(a);g.HEAPU8=x=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAPU32=ta=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=B=new Float64Array(a)}var va,wa=[],xa=[],ya=[],za=[],Aa=[];
function Ba(){var a=g.preRun.shift();wa.unshift(a)}var C=0,Ca=null,D=null;function la(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";r(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Da(a){return a.startsWith("data:application/octet-stream;base64,")}var E;E="shmup.wasm";if(!Da(E)){var Ea=E;E=g.locateFile?g.locateFile(Ea,q):q+Ea}
function Fa(a){try{if(a==E&&t)return new Uint8Array(t);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}catch(b){la(b)}}
function Ga(a){if(!t&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Fa(a)});if(ha)return new Promise(function(b,c){ha(a,function(d){b(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return Fa(a)})}
function Ha(a,b,c){return Ga(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){r("failed to asynchronously prepare wasm: "+d);la(d)})}
function Ia(a,b){var c=E;t||"function"!=typeof WebAssembly.instantiateStreaming||Da(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Ha(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){r("wasm streaming compile failed: "+e);r("falling back to ArrayBuffer instantiation");return Ha(c,a,b)})})}function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ja(a){for(;0<a.length;)a.shift()(g)}function Ka(a){var b=La();a();Ma(b)}var Na=0;function Oa(){for(var a=F.length-1;0<=a;--a)Pa(a);F=[];Qa=[]}var Qa=[];function Ra(){if(Na&&Sa.qc)for(var a=0;a<Qa.length;++a){var b=Qa[a];Qa.splice(a,1);--a;b.bd.apply(null,b.Rc)}}var F=[];function Pa(a){var b=F[a];b.target.removeEventListener(b.hc,b.Nc,b.ic);F.splice(a,1)}
function G(a){function b(d){++Na;Sa=a;Ra();a.kc(d);Ra();--Na}if(a.jc)a.Nc=b,a.target.addEventListener(a.hc,b,a.ic),F.push(a),Ta||(za.push(Oa),Ta=!0);else for(var c=0;c<F.length;++c)F[c].target==a.target&&F[c].hc==a.hc&&Pa(c--)}function Ua(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ta,Sa,Va,Wa,Xa,Ya,Za,$a,ab,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function H(a){a=2<a?w(a):a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function cb(a){return 0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var db=[];function I(a){var b=db[a];b||(a>=db.length&&(db.length=a+1),db[a]=b=va.get(a));return b}function eb(a,b,c,d,e,k){Va||(Va=J(256));a={target:H(a),hc:k,jc:d,kc:function(f=event){var m=f.target.id?f.target.id:"",n=Va;y(Ua(f.target),x,n+0,128);y(m,x,n+128,128);I(d)(e,n,b)&&f.preventDefault()},ic:c};G(a)}
function fb(a,b,c,d,e,k){Wa||(Wa=J(176));a={target:H(a),qc:!0,hc:k,jc:d,kc:function(f){var m=Wa;B[m>>3]=f.timeStamp;var n=m>>2;z[n+2]=f.location;z[n+3]=f.ctrlKey;z[n+4]=f.shiftKey;z[n+5]=f.altKey;z[n+6]=f.metaKey;z[n+7]=f.repeat;z[n+8]=f.charCode;z[n+9]=f.keyCode;z[n+10]=f.which;y(f.key||"",x,m+44,32);y(f.code||"",x,m+76,32);y(f.char||"",x,m+108,32);y(f.locale||"",x,m+140,32);I(d)(e,m,b)&&f.preventDefault()},ic:c};G(a)}
function gb(a,b,c){B[a>>3]=b.timeStamp;a>>=2;z[a+2]=b.screenX;z[a+3]=b.screenY;z[a+4]=b.clientX;z[a+5]=b.clientY;z[a+6]=b.ctrlKey;z[a+7]=b.shiftKey;z[a+8]=b.altKey;z[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;z[a+11]=b.movementX;z[a+12]=b.movementY;c=cb(c);z[a+13]=b.clientX-c.left;z[a+14]=b.clientY-c.top}
function K(a,b,c,d,e,k){Xa||(Xa=J(72));a=H(a);G({target:a,qc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,hc:k,jc:d,kc:function(f=event){gb(Xa,f,a);I(d)(e,Xa,b)&&f.preventDefault()},ic:c})}function hb(a,b,c,d,e){Ya||(Ya=J(260));G({target:a,hc:e,jc:d,kc:function(k=event){var f=Ya,m=document.pointerLockElement||document.nc||document.Ac||document.zc;z[f>>2]=!!m;var n=m&&m.id?m.id:"";y(Ua(m),x,f+4,128);y(n,x,f+132,128);I(d)(20,f,b)&&k.preventDefault()},ic:c})}
function ib(a,b,c,d,e){G({target:a,hc:e,jc:d,kc:function(k=event){I(d)(38,0,b)&&k.preventDefault()},ic:c})}function jb(a,b,c,d){Za||(Za=J(36));a=H(a);G({target:a,hc:"resize",jc:d,kc:function(e=event){if(e.target==a){var k=document.body;if(k){var f=Za;z[f>>2]=e.detail;z[f+4>>2]=k.clientWidth;z[f+8>>2]=k.clientHeight;z[f+12>>2]=innerWidth;z[f+16>>2]=innerHeight;z[f+20>>2]=outerWidth;z[f+24>>2]=outerHeight;z[f+28>>2]=pageXOffset;z[f+32>>2]=pageYOffset;I(d)(10,f,b)&&e.preventDefault()}}},ic:c})}
function kb(a,b,c,d,e,k){$a||($a=J(1696));a=H(a);G({target:a,qc:"touchstart"==k||"touchend"==k,hc:k,jc:d,kc:function(f){for(var m,n={},p=f.touches,u=0;u<p.length;++u)m=p[u],m.Bc=m.Dc=0,n[m.identifier]=m;for(u=0;u<f.changedTouches.length;++u)m=f.changedTouches[u],m.Bc=1,n[m.identifier]=m;for(u=0;u<f.targetTouches.length;++u)n[f.targetTouches[u].identifier].Dc=1;p=$a;B[p>>3]=f.timeStamp;var v=p>>2;z[v+3]=f.ctrlKey;z[v+4]=f.shiftKey;z[v+5]=f.altKey;z[v+6]=f.metaKey;v+=7;var ob=cb(a),pb=0;for(u in n)if(m=
n[u],z[v]=m.identifier,z[v+1]=m.screenX,z[v+2]=m.screenY,z[v+3]=m.clientX,z[v+4]=m.clientY,z[v+5]=m.pageX,z[v+6]=m.pageY,z[v+7]=m.Bc,z[v+8]=m.Dc,z[v+9]=m.clientX-ob.left,z[v+10]=m.clientY-ob.top,v+=13,31<++pb)break;z[p+8>>2]=pb;I(d)(e,p,b)&&f.preventDefault()},ic:c})}function lb(a,b,c,d,e,k){a={target:H(a),hc:k,jc:d,kc:function(f=event){I(d)(e,0,b)&&f.preventDefault()},ic:c};G(a)}
function mb(a,b,c,d){ab||(ab=J(104));G({target:a,qc:!0,hc:"wheel",jc:d,kc:function(e=event){var k=ab;gb(k,e,a);B[k+72>>3]=e.deltaX;B[k+80>>3]=e.deltaY;B[k+88>>3]=e.deltaZ;z[k+96>>2]=e.deltaMode;I(d)(9,k,b)&&e.preventDefault()},ic:c})}
function nb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,k){b.drawArraysInstancedANGLE(c,d,e,k)},a.drawElementsInstanced=function(c,d,e,k,f){b.drawElementsInstancedANGLE(c,d,e,k,f)})}
function qb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function rb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function sb(a){a.Tc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function tb(a){a.Vc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function ub(a){a.Xc=a.getExtension("WEBGL_multi_draw")}var vb=1,wb=[],L=[],xb=[],M=[],N=[],O=[],yb=[],zb=[],P=[],Ab={},Bb=4;function Q(a){Cb||(Cb=a)}function Db(a){for(var b=vb++,c=a.length;c<b;c++)a[c]=null;return b}
function Eb(a,b){a.nc||(a.nc=a.getContext,a.getContext=function(d,e){e=a.nc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Cc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Fb(c,b):0}function Fb(a,b){var c=Db(zb),d={Uc:c,attributes:b,version:b.Cc,uc:a};a.canvas&&(a.canvas.Qc=d);zb[c]=d;("undefined"==typeof b.yc||b.yc)&&Gb(d);return c}
function Gb(a){a||(a=R);if(!a.Pc){a.Pc=!0;var b=a.uc;nb(b);qb(b);rb(b);sb(b);tb(b);2<=a.version&&(b.xc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.xc)b.xc=b.getExtension("EXT_disjoint_timer_query");ub(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Cb,R,Hb=["default","low-power","high-performance"],Ib=[];
function S(a,b,c,d){for(var e=0;e<a;e++){var k=T[c](),f=k&&Db(d);k?(k.name=f,d[f]=k):Q(1282);z[b+4*e>>2]=f}}
function Jb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>R.version){Q(1282);return}c=2*(T.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>R.version){Q(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Q(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Q(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)z[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Q(1280);r("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Q(1280);r("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}z[b>>2]=c}else Q(1281)}
function Kb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function U(a){a-=5120;return 0==a?qa:1==a?x:2==a?ra:4==a?z:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?ta:sa}function V(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Lb(a,b,c,d,e){a=U(a);var k=V(a),f=Bb;return a.subarray(e>>k,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+f-1&-f)>>k)}
function W(a){var b=T.Mc;if(b){var c=b.pc[a];"number"==typeof c&&(b.pc[a]=c=T.getUniformLocation(b,b.Kc[a]+(0<c?"["+c+"]":"")));return c}Q(1282)}var X=[],Y=[];function Mb(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);na=!0}h(a,new ka(a))}function Nb(a){var b=pa(a)+1,c=Ob(b);y(a,qa,c,b);return c}for(var T,Z=0;32>Z;++Z)Ib.push(Array(Z));var Pb=new Float32Array(288);for(Z=0;288>Z;++Z)X[Z]=Pb.subarray(0,Z+1);var Qb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Qb.subarray(0,Z+1);
var bc={k:function(){la("")},O:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},R:function(a,b,c){a=H(a);if(!a)return-4;a=cb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},fb:function(a,b,c){x.copyWithin(a,b,b+c)},Ja:function(a,b){function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},eb:function(a){var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,k=e.min;d=Math.max(a,d);d+=
(65536-d%65536)%65536;a:{var f=ma.buffer;try{ma.grow(k.call(e,2147483648,d)-f.byteLength+65535>>>16);ua();var m=1;break a}catch(n){}m=void 0}if(m)return!0}return!1},U:function(a,b,c,d){eb(a,b,c,d,12,"blur");return 0},L:function(a,b,c){a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},V:function(a,b,c,d){eb(a,b,c,d,13,"focus");return 0},ca:function(a,b,c,d){fb(a,b,c,d,2,"keydown");return 0},aa:function(a,b,c,d){fb(a,b,c,d,1,"keypress");return 0},ba:function(a,b,c,d){fb(a,b,c,d,3,"keyup");return 0},
ka:function(a,b,c,d){K(a,b,c,d,5,"mousedown");return 0},fa:function(a,b,c,d){K(a,b,c,d,33,"mouseenter");return 0},ea:function(a,b,c,d){K(a,b,c,d,34,"mouseleave");return 0},ga:function(a,b,c,d){K(a,b,c,d,8,"mousemove");return 0},ja:function(a,b,c,d){K(a,b,c,d,6,"mouseup");return 0},X:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.nc||document.body.Ac||document.body.zc))return-1;a=H(a);if(!a)return-4;hb(a,b,c,d,"pointerlockchange");hb(a,b,c,d,"mozpointerlockchange");
hb(a,b,c,d,"webkitpointerlockchange");hb(a,b,c,d,"mspointerlockchange");return 0},W:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.nc||document.body.Ac||document.body.zc))return-1;a=H(a);if(!a)return-4;ib(a,b,c,d,"pointerlockerror");ib(a,b,c,d,"mozpointerlockerror");ib(a,b,c,d,"webkitpointerlockerror");ib(a,b,c,d,"mspointerlockerror");return 0},Sa:function(a,b,c,d){jb(a,b,c,d);return 0},Y:function(a,b,c,d){kb(a,b,c,d,25,"touchcancel");return 0},Z:function(a,b,c,
d){kb(a,b,c,d,23,"touchend");return 0},_:function(a,b,c,d){kb(a,b,c,d,24,"touchmove");return 0},$:function(a,b,c,d){kb(a,b,c,d,22,"touchstart");return 0},T:function(a,b,c,d){lb(a,b,c,d,31,"webglcontextlost");return 0},S:function(a,b,c,d){lb(a,b,c,d,32,"webglcontextrestored");return 0},da:function(a,b,c,d){a=H(a);return"undefined"!=typeof a.onwheel?(mb(a,b,c,d),0):-1},Lb:function(a,b){b>>=2;b={alpha:!!z[b],depth:!!z[b+1],stencil:!!z[b+2],antialias:!!z[b+3],premultipliedAlpha:!!z[b+4],preserveDrawingBuffer:!!z[b+
5],powerPreference:Hb[z[b+6]],failIfMajorPerformanceCaveat:!!z[b+7],Cc:z[b+8],Wc:z[b+9],yc:z[b+10],Oc:z[b+11],Yc:z[b+12],Zc:z[b+13]};a=H(a);return!a||b.Oc?0:Eb(a,b)},Cb:function(a,b){a=zb[a];b=w(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&nb(T);"OES_vertex_array_object"==b&&qb(T);"WEBGL_draw_buffers"==b&&rb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&sb(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&tb(T);"WEBGL_multi_draw"==b&&ub(T);return!!a.uc.getExtension(b)},
Aa:function(a){a>>=2;for(var b=0;14>b;++b)z[a+b]=0;z[a]=z[a+1]=z[a+3]=z[a+4]=z[a+8]=z[a+10]=1},Hb:function(a){R=zb[a];g.Sc=T=R&&R.uc;return!a||T?0:-5},f:function(a){T.activeTexture(a)},E:function(a,b){T.attachShader(L[a],O[b])},b:function(a,b){35051==a?T.wc=b:35052==a&&(T.mc=b);T.bindBuffer(a,wb[b])},j:function(a,b){T.bindFramebuffer(a,xb[b])},Ia:function(a,b){T.bindRenderbuffer(a,M[b])},g:function(a,b){T.bindSampler(a,P[b])},a:function(a,b){T.bindTexture(a,N[b])},P:function(a){T.bindVertexArray(yb[a])},
J:function(a,b,c,d){T.blendColor(a,b,c,d)},K:function(a,b){T.blendEquationSeparate(a,b)},M:function(a,b,c,d){T.blendFuncSeparate(a,b,c,d)},mb:function(a,b,c,d,e,k,f,m,n,p){T.blitFramebuffer(a,b,c,d,e,k,f,m,n,p)},La:function(a,b,c,d){2<=R.version?c&&b?T.bufferData(a,x,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?x.subarray(c,c+b):b,d)},p:function(a,b,c,d){2<=R.version?c&&T.bufferSubData(a,b,x,d,c):T.bufferSubData(a,b,x.subarray(d,d+c))},qa:function(a){return T.checkFramebufferStatus(a)},Gb:function(a,
b,c,d){T.clearBufferfi(a,b,c,d)},na:function(a,b,c){T.clearBufferfv(a,b,A,c>>2)},Fb:function(a,b,c){T.clearBufferiv(a,b,z,c>>2)},m:function(a,b,c,d){T.colorMask(!!a,!!b,!!c,!!d)},Kb:function(a){T.compileShader(O[a])},Fa:function(a,b,c,d,e,k,f,m){2<=R.version?T.mc||!f?T.compressedTexImage2D(a,b,c,d,e,k,f,m):T.compressedTexImage2D(a,b,c,d,e,k,x,m,f):T.compressedTexImage2D(a,b,c,d,e,k,m?x.subarray(m,m+f):null)},Da:function(a,b,c,d,e,k,f,m,n){T.mc?T.compressedTexImage3D(a,b,c,d,e,k,f,m,n):T.compressedTexImage3D(a,
b,c,d,e,k,f,x,n,m)},za:function(){var a=Db(L),b=T.createProgram();b.name=a;b.tc=b.rc=b.sc=0;b.vc=1;L[a]=b;return a},wa:function(a){var b=Db(O);O[b]=T.createShader(a);return b},G:function(a){T.cullFace(a)},Va:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=wb[d];e&&(T.deleteBuffer(e),e.name=0,wb[d]=null,d==T.wc&&(T.wc=0),d==T.mc&&(T.mc=0))}},e:function(a,b){for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=xb[d];e&&(T.deleteFramebuffer(e),e.name=0,xb[d]=null)}},y:function(a){if(a){var b=L[a];b?(T.deleteProgram(b),
b.name=0,L[a]=null):Q(1281)}},Ta:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=M[d];e&&(T.deleteRenderbuffer(e),e.name=0,M[d]=null)}},Q:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=P[d];e&&(T.deleteSampler(e),e.name=0,P[d]=null)}},u:function(a){if(a){var b=O[a];b?(T.deleteShader(b),O[a]=null):Q(1281)}},Ua:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=N[d];e&&(T.deleteTexture(e),e.name=0,N[d]=null)}},Ra:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];T.deleteVertexArray(yb[d]);
yb[d]=null}},x:function(a){T.depthFunc(a)},w:function(a){T.depthMask(!!a)},d:function(a){T.disable(a)},N:function(a){T.disableVertexAttribArray(a)},ob:function(a,b,c){T.drawArrays(a,b,c)},pb:function(a,b,c,d){T.drawArraysInstanced(a,b,c,d)},pa:function(a,b){for(var c=Ib[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];T.drawBuffers(c)},qb:function(a,b,c,d){T.drawElements(a,b,c,d)},rb:function(a,b,c,d,e){T.drawElementsInstanced(a,b,c,d,e)},i:function(a){T.enable(a)},Bb:function(a){T.enableVertexAttribArray(a)},ra:function(a,
b,c,d){T.framebufferRenderbuffer(a,b,c,M[d])},l:function(a,b,c,d,e){T.framebufferTexture2D(a,b,c,N[d],e)},A:function(a,b,c,d,e){T.framebufferTextureLayer(a,b,N[c],d,e)},H:function(a){T.frontFace(a)},Ma:function(a,b){S(a,b,"createBuffer",wb)},sa:function(a,b){S(a,b,"createFramebuffer",xb)},Ka:function(a,b){S(a,b,"createRenderbuffer",M)},Ba:function(a,b){S(a,b,"createSampler",P)},Ga:function(a,b){S(a,b,"createTexture",N)},Qa:function(a,b){S(a,b,"createVertexArray",yb)},Ib:function(a,b){return T.getAttribLocation(L[a],
w(b))},c:function(a,b){Jb(a,b)},xa:function(a,b,c,d){a=T.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,x,d,b):0;c&&(z[c>>2]=b)},D:function(a,b,c){if(c)if(a>=vb)Q(1281);else if(a=L[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b){if(!a.tc)for(b=0;b<T.getProgramParameter(a,35718);++b)a.tc=Math.max(a.tc,T.getActiveUniform(a,b).name.length+1);z[c>>2]=a.tc}else if(35722==b){if(!a.rc)for(b=0;b<T.getProgramParameter(a,35721);++b)a.rc=
Math.max(a.rc,T.getActiveAttrib(a,b).name.length+1);z[c>>2]=a.rc}else if(35381==b){if(!a.sc)for(b=0;b<T.getProgramParameter(a,35382);++b)a.sc=Math.max(a.sc,T.getActiveUniformBlockName(a,b).length+1);z[c>>2]=a.sc}else z[c>>2]=T.getProgramParameter(a,b);else Q(1281)},Jb:function(a,b,c,d){a=T.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,x,d,b):0;c&&(z[c>>2]=b)},ta:function(a,b,c){c?35716==b?(a=T.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),z[c>>2]=a?a.length+1:0):35720==
b?(a=T.getShaderSource(O[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=T.getShaderParameter(O[a],b):Q(1281)},Wa:function(a,b){if(2>R.version)return Q(1282),0;var c=Ab[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=T.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=pa(d)+1,k=J(e);y(d,x,k,e);return k}),c=Ab[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},o:function(a,b){b=w(b);if(a=L[a]){var c=a,d=c.pc,e=c.Lc,
k;if(!d)for(c.pc=d={},c.Kc={},k=0;k<T.getProgramParameter(c,35718);++k){var f=T.getActiveUniform(c,k);var m=f.name;f=f.size;var n=Kb(m);n=0<n?m.slice(0,n):m;var p=c.vc;c.vc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Kc[p++]=n}c=a.pc;d=0;e=b;k=Kb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Lc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else Q(1281);return-1},lb:function(a,b,c){for(var d=Ib[b],e=0;e<b;e++)d[e]=z[c+4*e>>2];T.invalidateFramebuffer(a,d)},ya:function(a){a=
L[a];T.linkProgram(a);a.pc=0;a.Lc={}},Pa:function(a,b){3317==a&&(Bb=b);T.pixelStorei(a,b)},I:function(a,b){T.polygonOffset(a,b)},nb:function(a){T.readBuffer(a)},Ha:function(a,b,c,d,e){T.renderbufferStorageMultisample(a,b,c,d,e)},F:function(a,b,c){T.samplerParameterf(P[a],b,c)},h:function(a,b,c){T.samplerParameteri(P[a],b,c)},oa:function(a,b,c,d){T.scissor(a,b,c,d)},va:function(a,b,c,d){for(var e="",k=0;k<b;++k){var f=d?z[d+4*k>>2]:-1;e+=w(z[c+4*k>>2],0>f?void 0:f)}T.shaderSource(O[a],e)},Oa:function(a,
b,c){T.stencilFunc(a,b,c)},ma:function(a,b,c,d){T.stencilFuncSeparate(a,b,c,d)},v:function(a){T.stencilMask(a)},Na:function(a,b,c){T.stencilOp(a,b,c)},la:function(a,b,c,d){T.stencilOpSeparate(a,b,c,d)},Ea:function(a,b,c,d,e,k,f,m,n){if(2<=R.version)if(T.mc)T.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=U(m);T.texImage2D(a,b,c,d,e,k,f,m,p,n>>V(p))}else T.texImage2D(a,b,c,d,e,k,f,m,null);else T.texImage2D(a,b,c,d,e,k,f,m,n?Lb(m,f,d,e,n):null)},Ca:function(a,b,c,d,e,k,f,m,n,p){if(T.mc)T.texImage3D(a,
b,c,d,e,k,f,m,n,p);else if(p){var u=U(n);T.texImage3D(a,b,c,d,e,k,f,m,n,u,p>>V(u))}else T.texImage3D(a,b,c,d,e,k,f,m,n,null)},kb:function(a,b,c,d,e,k,f,m,n){if(2<=R.version)if(T.mc)T.texSubImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=U(m);T.texSubImage2D(a,b,c,d,e,k,f,m,p,n>>V(p))}else T.texSubImage2D(a,b,c,d,e,k,f,m,null);else p=null,n&&(p=Lb(m,f,e,k,n)),T.texSubImage2D(a,b,c,d,e,k,f,m,p)},jb:function(a,b,c,d,e,k,f,m,n,p,u){if(T.mc)T.texSubImage3D(a,b,c,d,e,k,f,m,n,p,u);else if(u){var v=U(p);T.texSubImage3D(a,
b,c,d,e,k,f,m,n,p,v,u>>V(v))}else T.texSubImage3D(a,b,c,d,e,k,f,m,n,p,null)},Ab:function(a,b,c){if(2<=R.version)b&&T.uniform1fv(W(a),A,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},C:function(a,b){T.uniform1i(W(a),b)},wb:function(a,b,c){if(2<=R.version)b&&T.uniform1iv(W(a),z,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},zb:function(a,b,c){if(2<=
R.version)b&&T.uniform2fv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},vb:function(a,b,c){if(2<=R.version)b&&T.uniform2iv(W(a),z,c>>2,2*b);else{if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},yb:function(a,b,c){if(2<=R.version)b&&T.uniform3fv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],
e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},ub:function(a,b,c){if(2<=R.version)b&&T.uniform3iv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},xb:function(a,b,c){if(2<=R.version)b&&T.uniform4fv(W(a),A,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=A;c>>=2;for(var k=0;k<4*b;k+=4){var f=
c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=A.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},tb:function(a,b,c){if(2<=R.version)b&&T.uniform4iv(W(a),z,c>>2,4*b);else{if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},sb:function(a,b,c,d){if(2<=R.version)b&&T.uniformMatrix4fv(W(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],k=A;d>>=2;for(var f=
0;f<16*b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},n:function(a){a=L[a];T.useProgram(a);T.Mc=a},Db:function(a,b){T.vertexAttribDivisor(a,b)},Eb:function(a,b,c,d,e,k){T.vertexAttribPointer(a,b,c,!!d,e,k)},t:function(a,b,c,d){T.viewport(a,
b,c,d)},cb:function(){g.Ec=a=>{0!=Rb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Ec)},bb:function(){g.Jc=a=>{const b=a.clipboardData.getData("text");Ka(()=>{const c=Nb(b);Sb(c)})};window.addEventListener("paste",g.Jc)},ab:function(a){g.$c=[];a=w(a);a=document.getElementById(a);g.Fc=b=>{b.stopPropagation();b.preventDefault()};g.Gc=b=>{b.stopPropagation();b.preventDefault()};g.Hc=b=>{b.stopPropagation();b.preventDefault()};g.Ic=b=>{b.stopPropagation();b.preventDefault();
const c=b.dataTransfer.files;g.ad=c;Tb(c.length);for(let e=0;e<c.length;e++)Ka(()=>{const k=Nb(c[e].name);Ub(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Vb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Fc,!1);a.addEventListener("dragleave",g.Gc,!1);a.addEventListener("dragover",g.Hc,!1);a.addEventListener("drop",g.Ic,!1)},Ya:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},s:function(){const a=document.createElement("input");
a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Wb()});document.body.append(a)},r:function(){document.getElementById("_sokol_app_input_element").focus()},db:function(a){a=w(a);g.oc=document.getElementById(a);g.oc||console.log("sokol_app.h: invalid target:"+a);g.oc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},$a:function(){window.removeEventListener("beforeunload",g.Ec)},_a:function(){window.removeEventListener("paste",
g.Jc)},Za:function(a){a=w(a);a=document.getElementById(a);a.removeEventListener("dragenter",g.Fc);a.removeEventListener("dragleave",g.Gc);a.removeEventListener("dragover",g.Hc);a.removeEventListener("drop",g.Ic)},z:function(){g.oc&&g.oc.requestPointerLock&&g.oc.requestPointerLock()},Xa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(x.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},q:function(){document.getElementById("_sokol_app_input_element").blur()},gb:function(){return g.lc?g.lc.bufferSize:0},ib:function(a,b,c){g.fc=null;g.lc=null;"undefined"!==typeof AudioContext?g.fc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.fc=null,console.log("sokol_audio.h: no WebAudio support"));return g.fc?(console.log("sokol_audio.h: sample rate ",g.fc.sampleRate),g.lc=g.fc.createScriptProcessor(c,
0,b),g.lc.onaudioprocess=d=>{const e=d.outputBuffer.length,k=Xb(e);if(k){const f=d.outputBuffer.numberOfChannels;for(let m=0;m<f;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=A[(k>>2)+(f*p+m)]}}},g.lc.connect(g.fc.destination),a=()=>{g.fc&&"suspended"===g.fc.state&&g.fc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},hb:function(){return g.fc?g.fc.sampleRate:0},
ia:function(){const a=g.fc;null!==a&&(g.lc&&g.lc.disconnect(),a.close(),g.fc=null,g.lc=null)},B:function(a,b,c,d,e,k){b=w(b);const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),p=n.length;p<=k?(x.set(n,e),Yb(a,d,p)):Zb(a)}else $b(a,f.status)};f.send()},ha:function(a,b){b=w(b);
const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");ac(a,d)}else $b(a,c.status)};c.send()},ua:function(a,b){b=w(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;g.asm=c;ma=g.asm.Mb;ua();va=g.asm.bc;xa.unshift(g.asm.Nb);C--;g.monitorRunDependencies&&g.monitorRunDependencies(C);if(0==C&&(null!==Ca&&(clearInterval(Ca),Ca=null),D)){var d=D;D=null;d()}return c}var b={a:bc};C++;g.monitorRunDependencies&&g.monitorRunDependencies(C);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return r("Module.instantiateWasm callback failed with error: "+c),!1}Ia(b,function(c){a(c.instance)});return{}})();
var Wb=g.__sapp_emsc_notify_keyboard_hidden=function(){return(Wb=g.__sapp_emsc_notify_keyboard_hidden=g.asm.Ob).apply(null,arguments)},Sb=g.__sapp_emsc_onpaste=function(){return(Sb=g.__sapp_emsc_onpaste=g.asm.Pb).apply(null,arguments)},Rb=g.__sapp_html5_get_ask_leave_site=function(){return(Rb=g.__sapp_html5_get_ask_leave_site=g.asm.Qb).apply(null,arguments)},Tb=g.__sapp_emsc_begin_drop=function(){return(Tb=g.__sapp_emsc_begin_drop=g.asm.Rb).apply(null,arguments)},Ub=g.__sapp_emsc_drop=function(){return(Ub=
g.__sapp_emsc_drop=g.asm.Sb).apply(null,arguments)},Vb=g.__sapp_emsc_end_drop=function(){return(Vb=g.__sapp_emsc_end_drop=g.asm.Tb).apply(null,arguments)};g.__sapp_emsc_invoke_fetch_cb=function(){return(g.__sapp_emsc_invoke_fetch_cb=g.asm.Ub).apply(null,arguments)};var cc=g._main=function(){return(cc=g._main=g.asm.Vb).apply(null,arguments)},Xb=g.__saudio_emsc_pull=function(){return(Xb=g.__saudio_emsc_pull=g.asm.Wb).apply(null,arguments)};
g.__sargs_add_kvp=function(){return(g.__sargs_add_kvp=g.asm.Xb).apply(null,arguments)};
var ac=g.__sfetch_emsc_head_response=function(){return(ac=g.__sfetch_emsc_head_response=g.asm.Yb).apply(null,arguments)},Yb=g.__sfetch_emsc_get_response=function(){return(Yb=g.__sfetch_emsc_get_response=g.asm.Zb).apply(null,arguments)},$b=g.__sfetch_emsc_failed_http_status=function(){return($b=g.__sfetch_emsc_failed_http_status=g.asm._b).apply(null,arguments)},Zb=g.__sfetch_emsc_failed_buffer_too_small=function(){return(Zb=g.__sfetch_emsc_failed_buffer_too_small=g.asm.$b).apply(null,arguments)};
function J(){return(J=g.asm.ac).apply(null,arguments)}function La(){return(La=g.asm.cc).apply(null,arguments)}function Ma(){return(Ma=g.asm.dc).apply(null,arguments)}function Ob(){return(Ob=g.asm.ec).apply(null,arguments)}g.___start_em_js=81948;g.___stop_em_js=91963;var dc;D=function ec(){dc||fc();dc||(D=ec)};function gc(a=[]){var b=cc;a.unshift(ca);var c=a.length,d=Ob(4*(c+1)),e=d>>2;a.forEach(f=>{z[e++]=Nb(f)});z[e]=0;try{var k=b(c,d);Mb(k)}catch(f){f instanceof ka||"unwind"==f||h(1,f)}}
function fc(){var a=ba;function b(){if(!dc&&(dc=!0,g.calledRun=!0,!na)){Ja(xa);Ja(ya);if(g.onRuntimeInitialized)g.onRuntimeInitialized();hc&&gc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Aa.unshift(c)}Ja(Aa)}}if(!(0<C)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ba();Ja(wa);0<C||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var hc=!0;g.noInitialRun&&(hc=!1);fc();
