var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,h="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,l="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");l=h?ka.dirname(l)+"/":__dirname+"/";ha=(a,b)=>{a=a.startsWith("file://")?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):ka.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);
process.on("uncaughtException",function(a){if(!(a instanceof la))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(a){throw a;});da=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;if(!(b instanceof la)){var c=b;b&&"object"==typeof b&&b.stack&&(c=[b,b.stack]);q("exiting due to exception: "+c)}process.exit(a)};g.inspect=function(){return"[Emscripten Module object]"}}else if(ea||h)h?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},h&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=
c;d.send(null)};var ma=g.print||console.log.bind(console),q=g.printErr||console.warn.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var t;g.wasmBinary&&(t=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&na("no native wasm support detected");var oa,pa=!1,qa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function u(a,b){return a?ra(w,a,b):""}
function x(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var ta,w,ua,va,y,z,A,B;function wa(){var a=oa.buffer;g.HEAP8=ta=new Int8Array(a);g.HEAP16=ua=new Int16Array(a);g.HEAP32=y=new Int32Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=va=new Uint16Array(a);g.HEAPU32=z=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=B=new Float64Array(a)}var xa,ya=[],za=[],Aa=[],Ba=[],Ca=[];
function Da(){var a=g.preRun.shift();ya.unshift(a)}var C=0,Ea=null,D=null;function na(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";q(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Fa(a){return a.startsWith("data:application/octet-stream;base64,")}var E;E="shmup-ui.wasm";if(!Fa(E)){var Ga=E;E=g.locateFile?g.locateFile(Ga,l):l+Ga}
function Ha(a){try{if(a==E&&t)return new Uint8Array(t);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}catch(b){na(b)}}
function Ia(a){if(!t&&(ea||h)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Ha(a)});if(ia)return new Promise(function(b,c){ia(a,function(d){b(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return Ha(a)})}
function Ja(a,b,c){return Ia(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){q("failed to asynchronously prepare wasm: "+d);na(d)})}
function Ka(a,b){var c=E;t||"function"!=typeof WebAssembly.instantiateStreaming||Fa(c)||c.startsWith("file://")||fa||"function"!=typeof fetch?Ja(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){q("wasm streaming compile failed: "+e);q("falling back to ArrayBuffer instantiation");return Ja(c,a,b)})})}function la(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function La(a){for(;0<a.length;)a.shift()(g)}function Ma(a){var b=Na();a();Oa(b)}var Pa=0;function Qa(){for(var a=F.length-1;0<=a;--a)Ra(a);F=[];Sa=[]}var Sa=[];function Ta(){if(Pa&&Ua.zc)for(var a=0;a<Sa.length;++a){var b=Sa[a];Sa.splice(a,1);--a;b.md.apply(null,b.$c)}}var F=[];function Ra(a){var b=F[a];b.target.removeEventListener(b.qc,b.Wc,b.rc);F.splice(a,1)}
function G(a){function b(d){++Pa;Ua=a;Ta();a.tc(d);Ta();--Pa}if(a.sc)a.Wc=b,a.target.addEventListener(a.qc,b,a.rc),F.push(a),Va||(Ba.push(Qa),Va=!0);else for(var c=0;c<F.length;++c)F[c].target==a.target&&F[c].qc==a.qc&&Ra(c--)}function Wa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Va,Ua,Xa,Ya,Za,$a,ab,bb,cb,db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function H(a){a=2<a?u(a):a;return db[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function eb(a){return 0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var fb=[];function I(a){var b=fb[a];b||(a>=fb.length&&(fb.length=a+1),fb[a]=b=xa.get(a));return b}function gb(a,b,c,d,e,k){Xa||(Xa=J(256));a={target:H(a),qc:k,sc:d,tc:function(f=event){var m=f.target.id?f.target.id:"",n=Xa;x(Wa(f.target),w,n+0,128);x(m,w,n+128,128);I(d)(e,n,b)&&f.preventDefault()},rc:c};G(a)}
function hb(a,b,c,d,e,k){Ya||(Ya=J(176));a={target:H(a),zc:!0,qc:k,sc:d,tc:function(f){var m=Ya;B[m>>3]=f.timeStamp;var n=m>>2;y[n+2]=f.location;y[n+3]=f.ctrlKey;y[n+4]=f.shiftKey;y[n+5]=f.altKey;y[n+6]=f.metaKey;y[n+7]=f.repeat;y[n+8]=f.charCode;y[n+9]=f.keyCode;y[n+10]=f.which;x(f.key||"",w,m+44,32);x(f.code||"",w,m+76,32);x(f.char||"",w,m+108,32);x(f.locale||"",w,m+140,32);I(d)(e,m,b)&&f.preventDefault()},rc:c};G(a)}
function ib(a,b,c){B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;y[a+6]=b.ctrlKey;y[a+7]=b.shiftKey;y[a+8]=b.altKey;y[a+9]=b.metaKey;ua[2*a+20]=b.button;ua[2*a+21]=b.buttons;y[a+11]=b.movementX;y[a+12]=b.movementY;c=eb(c);y[a+13]=b.clientX-c.left;y[a+14]=b.clientY-c.top}
function K(a,b,c,d,e,k){Za||(Za=J(72));a=H(a);G({target:a,zc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,qc:k,sc:d,tc:function(f=event){ib(Za,f,a);I(d)(e,Za,b)&&f.preventDefault()},rc:c})}function jb(a,b,c,d,e){$a||($a=J(260));G({target:a,qc:e,sc:d,tc:function(k=event){var f=$a,m=document.pointerLockElement||document.xc||document.Mc||document.Lc;y[f>>2]=!!m;var n=m&&m.id?m.id:"";x(Wa(m),w,f+4,128);x(n,w,f+132,128);I(d)(20,f,b)&&k.preventDefault()},rc:c})}
function kb(a,b,c,d,e){G({target:a,qc:e,sc:d,tc:function(k=event){I(d)(38,0,b)&&k.preventDefault()},rc:c})}function lb(a,b,c,d){ab||(ab=J(36));a=H(a);G({target:a,qc:"resize",sc:d,tc:function(e=event){if(e.target==a){var k=document.body;if(k){var f=ab;y[f>>2]=e.detail;y[f+4>>2]=k.clientWidth;y[f+8>>2]=k.clientHeight;y[f+12>>2]=innerWidth;y[f+16>>2]=innerHeight;y[f+20>>2]=outerWidth;y[f+24>>2]=outerHeight;y[f+28>>2]=pageXOffset;y[f+32>>2]=pageYOffset;I(d)(10,f,b)&&e.preventDefault()}}},rc:c})}
function mb(a,b,c,d,e,k){bb||(bb=J(1696));a=H(a);G({target:a,zc:"touchstart"==k||"touchend"==k,qc:k,sc:d,tc:function(f){for(var m,n={},p=f.touches,r=0;r<p.length;++r)m=p[r],m.Ic=m.Kc=0,n[m.identifier]=m;for(r=0;r<f.changedTouches.length;++r)m=f.changedTouches[r],m.Ic=1,n[m.identifier]=m;for(r=0;r<f.targetTouches.length;++r)n[f.targetTouches[r].identifier].Kc=1;p=bb;B[p>>3]=f.timeStamp;var v=p>>2;y[v+3]=f.ctrlKey;y[v+4]=f.shiftKey;y[v+5]=f.altKey;y[v+6]=f.metaKey;v+=7;var pb=eb(a),qb=0;for(r in n)if(m=
n[r],y[v]=m.identifier,y[v+1]=m.screenX,y[v+2]=m.screenY,y[v+3]=m.clientX,y[v+4]=m.clientY,y[v+5]=m.pageX,y[v+6]=m.pageY,y[v+7]=m.Ic,y[v+8]=m.Kc,y[v+9]=m.clientX-pb.left,y[v+10]=m.clientY-pb.top,v+=13,31<++qb)break;y[p+8>>2]=qb;I(d)(e,p,b)&&f.preventDefault()},rc:c})}function nb(a,b,c,d,e,k){a={target:H(a),qc:k,sc:d,tc:function(f=event){I(d)(e,0,b)&&f.preventDefault()},rc:c};G(a)}
function ob(a,b,c,d){cb||(cb=J(104));G({target:a,zc:!0,qc:"wheel",sc:d,tc:function(e=event){var k=cb;ib(k,e,a);B[k+72>>3]=e.deltaX;B[k+80>>3]=e.deltaY;B[k+88>>3]=e.deltaZ;y[k+96>>2]=e.deltaMode;I(d)(9,k,b)&&e.preventDefault()},rc:c})}
function rb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,k){b.drawArraysInstancedANGLE(c,d,e,k)},a.drawElementsInstanced=function(c,d,e,k,f){b.drawElementsInstancedANGLE(c,d,e,k,f)})}
function sb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function tb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function ub(a){a.bd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function vb(a){a.dd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function wb(a){a.gd=a.getExtension("WEBGL_multi_draw")}var xb=1,yb=[],L=[],zb=[],M=[],N=[],O=[],Ab=[],Bb=[],P=[],Cb={},Db=4;function Q(a){Eb||(Eb=a)}function Fb(a){for(var b=xb++,c=a.length;c<b;c++)a[c]=null;return b}
function Gb(a,b){a.xc||(a.xc=a.getContext,a.getContext=function(d,e){e=a.xc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Jc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Hb(c,b):0}function Hb(a,b){var c=Fb(Bb),d={cd:c,attributes:b,version:b.Jc,Dc:a};a.canvas&&(a.canvas.Zc=d);Bb[c]=d;("undefined"==typeof b.Hc||b.Hc)&&Ib(d);return c}
function Ib(a){a||(a=R);if(!a.Yc){a.Yc=!0;var b=a.Dc;rb(b);sb(b);tb(b);ub(b);vb(b);2<=a.version&&(b.Gc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Gc)b.Gc=b.getExtension("EXT_disjoint_timer_query");wb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Eb,R,Jb=["default","low-power","high-performance"],Kb=[null,[],[]],Lb=[];
function S(a,b,c,d){for(var e=0;e<a;e++){var k=T[c](),f=k&&Fb(d);k?(k.name=f,d[f]=k):Q(1282);y[b+4*e>>2]=f}}
function Mb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>R.version){Q(1282);return}c=2*(T.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>R.version){Q(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Q(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Q(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Q(1280);q("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Q(1280);q("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}y[b>>2]=c}else Q(1281)}
function Nb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function U(a){a-=5120;return 0==a?ta:1==a?w:2==a?ua:4==a?y:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?z:va}function V(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Ob(a,b,c,d,e){a=U(a);var k=V(a),f=Db;return a.subarray(e>>k,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+f-1&-f)>>k)}
function W(a){var b=T.Vc;if(b){var c=b.yc[a];"number"==typeof c&&(b.yc[a]=c=T.getUniformLocation(b,b.Tc[a]+(0<c?"["+c+"]":"")));return c}Q(1282)}var X=[],Y=[];function Pb(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);pa=!0}da(a,new la(a))}function Qb(a){var b=sa(a)+1,c=Rb(b);x(a,ta,c,b);return c}for(var T,Z=0;32>Z;++Z)Lb.push(Array(Z));var Sb=new Float32Array(288);for(Z=0;288>Z;++Z)X[Z]=Sb.subarray(0,Z+1);var Tb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Tb.subarray(0,Z+1);
var ec={ja:function(){return 0},mb:function(){return 0},nb:function(){},k:function(){na("")},Q:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},S:function(a,b,c){a=H(a);if(!a)return-4;a=eb(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},jb:function(a,b,c){w.copyWithin(a,b,b+c)},La:function(a,b){function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ib:function(a){var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);
d=Math.min(d,a+100663296);var e=Math,k=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var f=oa.buffer;try{oa.grow(k.call(e,2147483648,d)-f.byteLength+65535>>>16);wa();var m=1;break a}catch(n){}m=void 0}if(m)return!0}return!1},V:function(a,b,c,d){gb(a,b,c,d,12,"blur");return 0},N:function(a,b,c){a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},W:function(a,b,c,d){gb(a,b,c,d,13,"focus");return 0},da:function(a,b,c,d){hb(a,b,c,d,2,"keydown");return 0},ba:function(a,b,c,d){hb(a,b,c,d,1,"keypress");
return 0},ca:function(a,b,c,d){hb(a,b,c,d,3,"keyup");return 0},oa:function(a,b,c,d){K(a,b,c,d,5,"mousedown");return 0},ga:function(a,b,c,d){K(a,b,c,d,33,"mouseenter");return 0},fa:function(a,b,c,d){K(a,b,c,d,34,"mouseleave");return 0},ia:function(a,b,c,d){K(a,b,c,d,8,"mousemove");return 0},na:function(a,b,c,d){K(a,b,c,d,6,"mouseup");return 0},Y:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.xc||document.body.Mc||document.body.Lc))return-1;a=H(a);
if(!a)return-4;jb(a,b,c,d,"pointerlockchange");jb(a,b,c,d,"mozpointerlockchange");jb(a,b,c,d,"webkitpointerlockchange");jb(a,b,c,d,"mspointerlockchange");return 0},X:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.xc||document.body.Mc||document.body.Lc))return-1;a=H(a);if(!a)return-4;kb(a,b,c,d,"pointerlockerror");kb(a,b,c,d,"mozpointerlockerror");kb(a,b,c,d,"webkitpointerlockerror");kb(a,b,c,d,"mspointerlockerror");return 0},Va:function(a,b,c,d){lb(a,b,c,d);return 0},
Z:function(a,b,c,d){mb(a,b,c,d,25,"touchcancel");return 0},_:function(a,b,c,d){mb(a,b,c,d,23,"touchend");return 0},$:function(a,b,c,d){mb(a,b,c,d,24,"touchmove");return 0},aa:function(a,b,c,d){mb(a,b,c,d,22,"touchstart");return 0},U:function(a,b,c,d){nb(a,b,c,d,31,"webglcontextlost");return 0},T:function(a,b,c,d){nb(a,b,c,d,32,"webglcontextrestored");return 0},ea:function(a,b,c,d){a=H(a);return"undefined"!=typeof a.onwheel?(ob(a,b,c,d),0):-1},Vb:function(a,b){b>>=2;b={alpha:!!y[b],depth:!!y[b+1],
stencil:!!y[b+2],antialias:!!y[b+3],premultipliedAlpha:!!y[b+4],preserveDrawingBuffer:!!y[b+5],powerPreference:Jb[y[b+6]],failIfMajorPerformanceCaveat:!!y[b+7],Jc:y[b+8],ed:y[b+9],Hc:y[b+10],Xc:y[b+11],hd:y[b+12],jd:y[b+13]};a=H(a);return!a||b.Xc?0:Gb(a,b)},Mb:function(a,b){a=Bb[a];b=u(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&rb(T);"OES_vertex_array_object"==b&&sb(T);"WEBGL_draw_buffers"==b&&tb(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&ub(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==
b&&vb(T);"WEBGL_multi_draw"==b&&wb(T);return!!a.Dc.getExtension(b)},Ba:function(a){a>>=2;for(var b=0;14>b;++b)y[a+b]=0;y[a]=y[a+1]=y[a+3]=y[a+4]=y[a+8]=y[a+10]=1},Pb:function(a){R=Bb[a];g.ad=T=R&&R.Dc;return!a||T?0:-5},ha:function(){return 52},lb:function(){return 52},hb:function(){return 70},kb:function(a,b,c,d){for(var e=0,k=0;k<c;k++){var f=z[b>>2],m=z[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=w[f+n],r=Kb[a];0===p||10===p?((1===a?ma:q)(ra(r,0)),r.length=0):r.push(p)}e+=m}z[d>>2]=e;return 0},f:function(a){T.activeTexture(a)},
F:function(a,b){T.attachShader(L[a],O[b])},b:function(a,b){35051==a?T.Fc=b:35052==a&&(T.vc=b);T.bindBuffer(a,yb[b])},j:function(a,b){T.bindFramebuffer(a,zb[b])},Ja:function(a,b){T.bindRenderbuffer(a,M[b])},g:function(a,b){T.bindSampler(a,P[b])},a:function(a,b){T.bindTexture(a,N[b])},P:function(a){T.bindVertexArray(Ab[a])},K:function(a,b,c,d){T.blendColor(a,b,c,d)},L:function(a,b){T.blendEquationSeparate(a,b)},M:function(a,b,c,d){T.blendFuncSeparate(a,b,c,d)},ub:function(a,b,c,d,e,k,f,m,n,p){T.blitFramebuffer(a,
b,c,d,e,k,f,m,n,p)},Ma:function(a,b,c,d){2<=R.version?c&&b?T.bufferData(a,w,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?w.subarray(c,c+b):b,d)},r:function(a,b,c,d){2<=R.version?c&&T.bufferSubData(a,b,w,d,c):T.bufferSubData(a,b,w.subarray(d,d+c))},ta:function(a){return T.checkFramebufferStatus(a)},Ob:function(a,b,c,d){T.clearBufferfi(a,b,c,d)},ra:function(a,b,c){T.clearBufferfv(a,b,A,c>>2)},Nb:function(a,b,c){T.clearBufferiv(a,b,y,c>>2)},n:function(a,b,c,d){T.colorMask(!!a,!!b,!!c,!!d)},Sb:function(a){T.compileShader(O[a])},
Ga:function(a,b,c,d,e,k,f,m){2<=R.version?T.vc||!f?T.compressedTexImage2D(a,b,c,d,e,k,f,m):T.compressedTexImage2D(a,b,c,d,e,k,w,m,f):T.compressedTexImage2D(a,b,c,d,e,k,m?w.subarray(m,m+f):null)},Ea:function(a,b,c,d,e,k,f,m,n){T.vc?T.compressedTexImage3D(a,b,c,d,e,k,f,m,n):T.compressedTexImage3D(a,b,c,d,e,k,f,w,n,m)},Aa:function(){var a=Fb(L),b=T.createProgram();b.name=a;b.Cc=b.Ac=b.Bc=0;b.Ec=1;L[a]=b;return a},Ub:function(a){var b=Fb(O);O[b]=T.createShader(a);return b},H:function(a){T.cullFace(a)},
Wa:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=yb[d];e&&(T.deleteBuffer(e),e.name=0,yb[d]=null,d==T.Fc&&(T.Fc=0),d==T.vc&&(T.vc=0))}},e:function(a,b){for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=zb[d];e&&(T.deleteFramebuffer(e),e.name=0,zb[d]=null)}},z:function(a){if(a){var b=L[a];b?(T.deleteProgram(b),b.name=0,L[a]=null):Q(1281)}},Ta:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=M[d];e&&(T.deleteRenderbuffer(e),e.name=0,M[d]=null)}},R:function(a,b){for(var c=0;c<a;c++){var d=y[b+
4*c>>2],e=P[d];e&&(T.deleteSampler(e),e.name=0,P[d]=null)}},v:function(a){if(a){var b=O[a];b?(T.deleteShader(b),O[a]=null):Q(1281)}},Ua:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=N[d];e&&(T.deleteTexture(e),e.name=0,N[d]=null)}},Sa:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2];T.deleteVertexArray(Ab[d]);Ab[d]=null}},y:function(a){T.depthFunc(a)},x:function(a){T.depthMask(!!a)},d:function(a){T.disable(a)},O:function(a){T.disableVertexAttribArray(a)},wb:function(a,b,c){T.drawArrays(a,
b,c)},xb:function(a,b,c,d){T.drawArraysInstanced(a,b,c,d)},sa:function(a,b){for(var c=Lb[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];T.drawBuffers(c)},yb:function(a,b,c,d){T.drawElements(a,b,c,d)},zb:function(a,b,c,d,e){T.drawElementsInstanced(a,b,c,d,e)},i:function(a){T.enable(a)},Jb:function(a){T.enableVertexAttribArray(a)},ua:function(a,b,c,d){T.framebufferRenderbuffer(a,b,c,M[d])},m:function(a,b,c,d,e){T.framebufferTexture2D(a,b,c,N[d],e)},B:function(a,b,c,d,e){T.framebufferTextureLayer(a,b,N[c],d,e)},I:function(a){T.frontFace(a)},
Na:function(a,b){S(a,b,"createBuffer",yb)},va:function(a,b){S(a,b,"createFramebuffer",zb)},Ka:function(a,b){S(a,b,"createRenderbuffer",M)},Ca:function(a,b){S(a,b,"createSampler",P)},Ha:function(a,b){S(a,b,"createTexture",N)},Ra:function(a,b){S(a,b,"createVertexArray",Ab)},Qb:function(a,b){return T.getAttribLocation(L[a],u(b))},c:function(a,b){Mb(a,b)},ya:function(a,b,c,d){a=T.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?x(a,w,d,b):0;c&&(y[c>>2]=b)},E:function(a,b,c){if(c)if(a>=
xb)Q(1281);else if(a=L[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.Cc)for(b=0;b<T.getProgramParameter(a,35718);++b)a.Cc=Math.max(a.Cc,T.getActiveUniform(a,b).name.length+1);y[c>>2]=a.Cc}else if(35722==b){if(!a.Ac)for(b=0;b<T.getProgramParameter(a,35721);++b)a.Ac=Math.max(a.Ac,T.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.Ac}else if(35381==b){if(!a.Bc)for(b=0;b<T.getProgramParameter(a,35382);++b)a.Bc=Math.max(a.Bc,T.getActiveUniformBlockName(a,
b).length+1);y[c>>2]=a.Bc}else y[c>>2]=T.getProgramParameter(a,b);else Q(1281)},Rb:function(a,b,c,d){a=T.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?x(a,w,d,b):0;c&&(y[c>>2]=b)},wa:function(a,b,c){c?35716==b?(a=T.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(O[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=T.getShaderParameter(O[a],b):Q(1281)},Xa:function(a,b){if(2>R.version)return Q(1282),0;var c=Cb[a];if(c)return 0>b||b>=c.length?
(Q(1281),0):c[b];switch(a){case 7939:return c=T.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=sa(d)+1,k=J(e);x(d,w,k,e);return k}),c=Cb[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},q:function(a,b){b=u(b);if(a=L[a]){var c=a,d=c.yc,e=c.Uc,k;if(!d)for(c.yc=d={},c.Tc={},k=0;k<T.getProgramParameter(c,35718);++k){var f=T.getActiveUniform(c,k);var m=f.name;f=f.size;var n=Nb(m);n=0<n?m.slice(0,n):m;var p=c.Ec;c.Ec+=f;e[n]=[f,p];for(m=
0;m<f;++m)d[p]=m,c.Tc[p++]=n}c=a.yc;d=0;e=b;k=Nb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Uc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else Q(1281);return-1},tb:function(a,b,c){for(var d=Lb[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];T.invalidateFramebuffer(a,d)},za:function(a){a=L[a];T.linkProgram(a);a.yc=0;a.Uc={}},Qa:function(a,b){3317==a&&(Db=b);T.pixelStorei(a,b)},J:function(a,b){T.polygonOffset(a,b)},vb:function(a){T.readBuffer(a)},Ia:function(a,b,c,d,e){T.renderbufferStorageMultisample(a,
b,c,d,e)},G:function(a,b,c){T.samplerParameterf(P[a],b,c)},h:function(a,b,c){T.samplerParameteri(P[a],b,c)},p:function(a,b,c,d){T.scissor(a,b,c,d)},Tb:function(a,b,c,d){for(var e="",k=0;k<b;++k){var f=d?y[d+4*k>>2]:-1;e+=u(y[c+4*k>>2],0>f?void 0:f)}T.shaderSource(O[a],e)},Pa:function(a,b,c){T.stencilFunc(a,b,c)},qa:function(a,b,c,d){T.stencilFuncSeparate(a,b,c,d)},w:function(a){T.stencilMask(a)},Oa:function(a,b,c){T.stencilOp(a,b,c)},pa:function(a,b,c,d){T.stencilOpSeparate(a,b,c,d)},Fa:function(a,
b,c,d,e,k,f,m,n){if(2<=R.version)if(T.vc)T.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=U(m);T.texImage2D(a,b,c,d,e,k,f,m,p,n>>V(p))}else T.texImage2D(a,b,c,d,e,k,f,m,null);else T.texImage2D(a,b,c,d,e,k,f,m,n?Ob(m,f,d,e,n):null)},Da:function(a,b,c,d,e,k,f,m,n,p){if(T.vc)T.texImage3D(a,b,c,d,e,k,f,m,n,p);else if(p){var r=U(n);T.texImage3D(a,b,c,d,e,k,f,m,n,r,p>>V(r))}else T.texImage3D(a,b,c,d,e,k,f,m,n,null)},sb:function(a,b,c,d,e,k,f,m,n){if(2<=R.version)if(T.vc)T.texSubImage2D(a,b,c,d,e,k,f,m,
n);else if(n){var p=U(m);T.texSubImage2D(a,b,c,d,e,k,f,m,p,n>>V(p))}else T.texSubImage2D(a,b,c,d,e,k,f,m,null);else p=null,n&&(p=Ob(m,f,e,k,n)),T.texSubImage2D(a,b,c,d,e,k,f,m,p)},rb:function(a,b,c,d,e,k,f,m,n,p,r){if(T.vc)T.texSubImage3D(a,b,c,d,e,k,f,m,n,p,r);else if(r){var v=U(p);T.texSubImage3D(a,b,c,d,e,k,f,m,n,p,v,r>>V(v))}else T.texSubImage3D(a,b,c,d,e,k,f,m,n,p,null)},Ib:function(a,b,c){if(2<=R.version)b&&T.uniform1fv(W(a),A,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>
2];else d=A.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},D:function(a,b){T.uniform1i(W(a),b)},Eb:function(a,b,c){if(2<=R.version)b&&T.uniform1iv(W(a),y,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},Hb:function(a,b,c){if(2<=R.version)b&&T.uniform2fv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},Db:function(a,
b,c){if(2<=R.version)b&&T.uniform2iv(W(a),y,c>>2,2*b);else{if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},Gb:function(a,b,c){if(2<=R.version)b&&T.uniform3fv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},Cb:function(a,b,c){if(2<=R.version)b&&T.uniform3iv(W(a),y,c>>2,3*b);
else{if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},Fb:function(a,b,c){if(2<=R.version)b&&T.uniform4fv(W(a),A,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=A;c>>=2;for(var k=0;k<4*b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=A.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},Bb:function(a,b,c){if(2<=R.version)b&&T.uniform4iv(W(a),y,c>>2,4*b);else{if(72>=b)for(var d=
Y[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},Ab:function(a,b,c,d){if(2<=R.version)b&&T.uniformMatrix4fv(W(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],k=A;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=k[m];e[f+1]=k[m+1];e[f+2]=k[m+2];e[f+3]=k[m+3];e[f+4]=k[m+4];e[f+5]=k[m+5];e[f+6]=k[m+6];e[f+7]=k[m+7];e[f+8]=k[m+8];e[f+9]=k[m+9];e[f+10]=k[m+10];e[f+11]=k[m+11];e[f+12]=
k[m+12];e[f+13]=k[m+13];e[f+14]=k[m+14];e[f+15]=k[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},o:function(a){a=L[a];T.useProgram(a);T.Vc=a},Kb:function(a,b){T.vertexAttribDivisor(a,b)},Lb:function(a,b,c,d,e,k){T.vertexAttribPointer(a,b,c,!!d,e,k)},l:function(a,b,c,d){T.viewport(a,b,c,d)},fb:function(){g.Nc=a=>{0!=Ub()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Nc)},eb:function(){g.Sc=a=>{const b=a.clipboardData.getData("text");Ma(()=>
{const c=Qb(b);Vb(c)})};window.addEventListener("paste",g.Sc)},db:function(a){g.kd=[];a=u(a);a=document.getElementById(a);g.Oc=b=>{b.stopPropagation();b.preventDefault()};g.Pc=b=>{b.stopPropagation();b.preventDefault()};g.Qc=b=>{b.stopPropagation();b.preventDefault()};g.Rc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.ld=c;Wb(c.length);for(let e=0;e<c.length;e++)Ma(()=>{const k=Qb(c[e].name);Xb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&
(d|=8);Yb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",g.Oc,!1);a.addEventListener("dragleave",g.Pc,!1);a.addEventListener("dragover",g.Qc,!1);a.addEventListener("drop",g.Rc,!1)},Za:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},u:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Zb()});document.body.append(a)},t:function(){document.getElementById("_sokol_app_input_element").focus()},
gb:function(a){a=u(a);g.wc=document.getElementById(a);g.wc||console.log("sokol_app.h: invalid target:"+a);g.wc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},cb:function(){window.removeEventListener("beforeunload",g.Nc)},bb:function(){window.removeEventListener("paste",g.Sc)},ab:function(a){a=u(a);a=document.getElementById(a);a.removeEventListener("dragenter",g.Oc);a.removeEventListener("dragleave",g.Pc);a.removeEventListener("dragover",g.Qc);a.removeEventListener("drop",
g.Rc)},A:function(){g.wc&&g.wc.requestPointerLock&&g.wc.requestPointerLock()},$a:function(a,b){if(g.wc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.wc.style.cursor=a}},Ya:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(w.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},s:function(){document.getElementById("_sokol_app_input_element").blur()},_a:function(a){a=u(a);const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize",
"off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ob:function(){return g.uc?g.uc.bufferSize:0},qb:function(a,b,c){g.pc=null;g.uc=null;"undefined"!==typeof AudioContext?g.pc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.pc=null,console.log("sokol_audio.h: no WebAudio support"));return g.pc?(console.log("sokol_audio.h: sample rate ",
g.pc.sampleRate),g.uc=g.pc.createScriptProcessor(c,0,b),g.uc.onaudioprocess=d=>{const e=d.outputBuffer.length,k=$b(e);if(k){const f=d.outputBuffer.numberOfChannels;for(let m=0;m<f;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=A[(k>>2)+(f*p+m)]}}},g.uc.connect(g.pc.destination),a=()=>{g.pc&&"suspended"===g.pc.state&&g.pc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},pb:function(){return g.pc?g.pc.sampleRate:0},ma:function(){const a=g.pc;null!==a&&(g.uc&&g.uc.disconnect(),a.close(),g.pc=null,g.uc=null)},C:function(a,b,c,d,e,k){b=u(b);const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),p=n.length;p<=k?(w.set(n,e),ac(a,d,p)):bc(a)}else cc(a,
f.status)};f.send()},la:function(a,b){b=u(b);const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");dc(a,d)}else cc(a,c.status)};c.send()},ka:function(){return navigator.userAgent.includes("Macintosh")?1:0},xa:function(a,b){b=u(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;g.asm=c;oa=g.asm.Wb;wa();xa=g.asm.lc;za.unshift(g.asm.Xb);C--;g.monitorRunDependencies&&g.monitorRunDependencies(C);if(0==C&&(null!==Ea&&(clearInterval(Ea),Ea=null),D)){var d=D;D=null;d()}return c}var b={a:ec};C++;g.monitorRunDependencies&&g.monitorRunDependencies(C);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return q("Module.instantiateWasm callback failed with error: "+c),!1}Ka(b,function(c){a(c.instance)});return{}})();
var Zb=g.__sapp_emsc_notify_keyboard_hidden=function(){return(Zb=g.__sapp_emsc_notify_keyboard_hidden=g.asm.Yb).apply(null,arguments)},Vb=g.__sapp_emsc_onpaste=function(){return(Vb=g.__sapp_emsc_onpaste=g.asm.Zb).apply(null,arguments)},Ub=g.__sapp_html5_get_ask_leave_site=function(){return(Ub=g.__sapp_html5_get_ask_leave_site=g.asm._b).apply(null,arguments)},Wb=g.__sapp_emsc_begin_drop=function(){return(Wb=g.__sapp_emsc_begin_drop=g.asm.$b).apply(null,arguments)},Xb=g.__sapp_emsc_drop=function(){return(Xb=
g.__sapp_emsc_drop=g.asm.ac).apply(null,arguments)},Yb=g.__sapp_emsc_end_drop=function(){return(Yb=g.__sapp_emsc_end_drop=g.asm.bc).apply(null,arguments)};g.__sapp_emsc_invoke_fetch_cb=function(){return(g.__sapp_emsc_invoke_fetch_cb=g.asm.cc).apply(null,arguments)};var fc=g._main=function(){return(fc=g._main=g.asm.dc).apply(null,arguments)},$b=g.__saudio_emsc_pull=function(){return($b=g.__saudio_emsc_pull=g.asm.ec).apply(null,arguments)};
g.__sargs_add_kvp=function(){return(g.__sargs_add_kvp=g.asm.fc).apply(null,arguments)};
var dc=g.__sfetch_emsc_head_response=function(){return(dc=g.__sfetch_emsc_head_response=g.asm.gc).apply(null,arguments)},ac=g.__sfetch_emsc_get_response=function(){return(ac=g.__sfetch_emsc_get_response=g.asm.hc).apply(null,arguments)},cc=g.__sfetch_emsc_failed_http_status=function(){return(cc=g.__sfetch_emsc_failed_http_status=g.asm.ic).apply(null,arguments)},bc=g.__sfetch_emsc_failed_buffer_too_small=function(){return(bc=g.__sfetch_emsc_failed_buffer_too_small=g.asm.jc).apply(null,arguments)};
function J(){return(J=g.asm.kc).apply(null,arguments)}function Na(){return(Na=g.asm.mc).apply(null,arguments)}function Oa(){return(Oa=g.asm.nc).apply(null,arguments)}function Rb(){return(Rb=g.asm.oc).apply(null,arguments)}g.___start_em_js=105492;g.___stop_em_js=115601;var gc;D=function hc(){gc||ic();gc||(D=hc)};function jc(a=[]){var b=fc;a.unshift(ca);var c=a.length,d=Rb(4*(c+1)),e=d>>2;a.forEach(f=>{y[e++]=Qb(f)});y[e]=0;try{var k=b(c,d);Pb(k)}catch(f){f instanceof la||"unwind"==f||da(1,f)}}
function ic(){var a=ba;function b(){if(!gc&&(gc=!0,g.calledRun=!0,!pa)){La(za);La(Aa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();kc&&jc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Ca.unshift(c)}La(Ca)}}if(!(0<C)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Da();La(ya);0<C||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var kc=!0;g.noInitialRun&&(kc=!1);ic();
